# name of your application
APPLICATION = octa-flash-example
APPLICATION_VERSION = 0.3.0

# platform for which the application will be built
PLATFORM ?= octa_stm

DEBUG = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../../..
FOLDER = examples

include $(STACKBASE)/core/Makefile.core