# name of your application
APPLICATION = temperature-humidity-example
APPLICATION_VERSION = 0.1.0

# platform for which the application will be built
PLATFORM ?= octa

# Set PRINT_FLOATS to 1 to enable linker flags enabling float printf & sprintf
PRINT_FLOATS = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../../..
FOLDER = examples

include $(STACKBASE)/core/Makefile.core 