# name of your application
APPLICATION = scd30-example
APPLICATION_VERSION = 0.1.1

# platform for which the application will be built
PLATFORM ?= octa

SHIELDS += SCD30
SCD30_CONNECTOR = 1

DEBUG = 1

# Set PRINT_FLOATS to 1 to enable linker flags enabling float printf & sprintf
PRINT_FLOATS = 1

# Path to the octa-stack base directory:
STACKBASE ?= ../../..
FOLDER = examples

include $(STACKBASE)/core/Makefile.core